spring:
  application:
    name: mero-backend
  messages:
    encoding: UTF-8

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:86400000}