spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

storage:
  url: ${STORAGE_URL}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}
  bucket:
    images: ${STORAGE_BUCKET_IMAGES}
    docs: ${STORAGE_BUCKET_DOCS}
  signed-url-expiry-seconds: ${STORAGE_SIGNED_URL_EXPIRY_SECONDS:36000}

logging:
  level:
    root: WARN
    io.mero.app: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
