spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-request-size: 50MB
  mail:
    host: smtp.resend.com
    port: 465
    username: ${RESEND_USERNAME}
    password: ${RESEND_API_KEY}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

storage:
  url: ${STORAGE_URL}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}
  bucket:
    images: ${STORAGE_BUCKET_IMAGES}
    docs: ${STORAGE_BUCKET_DOCS}
  signed-url-expiry-seconds: ${STORAGE_SIGNED_URL_EXPIRY_SECONDS:3600}

app:
  base-url: ${APP_BASE_URL}
  mail:
    from: ${MAIL_FROM_ADDRESS}

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

